services:
  
  nginx: 
    container_name: rockets_server
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /home/rocket/git-workspace/hwang_git/rockets/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /home/rocket/git-workspace/hwang_git/rockets/rockets/static/:/static