# Generated by Django 4.2.7 on 2023-11-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BackendLanguage',
            fields=[
                ('backend_no', models.AutoField(db_column='BACKEND_NO', primary_key=True, serialize=False)),
                ('backend_name', models.CharField(db_column='BACKEND_NAME', max_length=255)),
            ],
            options={
                'db_table': 'Backend_Language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbList',
            fields=[
                ('db_no', models.AutoField(db_column='DB_NO', primary_key=True, serialize=False)),
                ('db_name', models.CharField(db_column='DB_NAME', max_length=255)),
            ],
            options={
                'db_table': 'DB_List',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_no', models.AutoField(db_column='REGION_NO', primary_key=True, serialize=False)),
                ('region_code', models.CharField(db_column='REGION_CODE', max_length=255)),
                ('region_name', models.CharField(db_column='REGION_NAME', max_length=255)),
            ],
            options={
                'db_table': 'REGION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serviceaws',
            fields=[
                ('service_no', models.AutoField(db_column='SERVICE_NO', primary_key=True, serialize=False)),
                ('service_name', models.CharField(blank=True, db_column='SERVICE_NAME', max_length=255, null=True)),
                ('ecr_uri', models.CharField(blank=True, db_column='ECR_URI', max_length=255, null=True)),
                ('load_balancer_name', models.CharField(blank=True, db_column='LOAD_BALANCER_NAME', max_length=255, null=True)),
                ('s3_arn', models.CharField(blank=True, db_column='S3_ARN', max_length=255, null=True)),
                ('cloudfront_dns', models.CharField(blank=True, db_column='CLOUDFRONT_DNS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ServiceAws',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('uno', models.AutoField(db_column='UNO', primary_key=True, serialize=False)),
                ('uid', models.CharField(db_column='UID', max_length=255)),
                ('upwd', models.CharField(db_column='UPWD', max_length=255)),
                ('uname', models.CharField(db_column='UNAME', max_length=255)),
                ('email', models.CharField(db_column='EMAIL', max_length=255)),
                ('regist_date', models.DateField(db_column='REGIST_DATE')),
            ],
            options={
                'db_table': 'UserInfo',
                'managed': False,
            },
        ),
    ]
