# Generated by Django 4.2.7 on 2023-11-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocket_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='region',
            table='Region',
        ),
    ]
