apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.app.name }}                                                             # deployment.yaml의 metadata.name
  type: NodePort
  ports:
    - port: 80                                                              # 서비스 리슨 포트
      targetPort: {{ .Values.container.port }}                                                           # pod 포트, deployment.yaml의 spec.template.spec.containerPort.ports.containerPort
      protocol: TCP
      name: http

    - port: 443                                                              # 서비스 리슨 포트
      targetPort: {{ .Values.container.port }}                                                           # pod 포트, deployment.yaml의 spec.template.spec.containerPort.ports.containerPort
      protocol: TCP
      name: https
